defmodule CloseTheLoop.Repo.TenantMigrations.AddAiResolutionStatusToReports do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:reports, prefix: prefix()) do
      add :ai_resolution_status, :text
    end
  end

  def down do
    alter table(:reports, prefix: prefix()) do
      remove :ai_resolution_status
    end
  end
end
