defmodule CloseTheLoop.Repo.TenantMigrations.AddIssueCategory do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:issues, prefix: prefix()) do
      add :category, :text
    end
  end

  def down do
    alter table(:issues, prefix: prefix()) do
      remove :category
    end
  end
end
