defmodule CloseTheLoop.Repo.TenantMigrations.AddTenantsAndFeedback do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:reports, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :body, :text, null: false
      add :normalized_body, :text, null: false
      add :source, :text, null: false
      add :reporter_phone, :text
      add :consent, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :location_id, :uuid, null: false
      add :issue_id, :uuid, null: false
    end

    create table(:locations, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:reports, prefix: prefix()) do
      modify :location_id,
             references(:locations,
               column: :id,
               name: "reports_location_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:locations, prefix: prefix()) do
      add :name, :text, null: false
      add :full_path, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :parent_id,
          references(:locations,
            column: :id,
            name: "locations_parent_id_fkey",
            type: :uuid,
            prefix: prefix()
          )
    end

    create table(:issues, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:reports, prefix: prefix()) do
      modify :issue_id,
             references(:issues,
               column: :id,
               name: "reports_issue_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:issues, prefix: prefix()) do
      add :title, :text, null: false
      add :description, :text, null: false
      add :normalized_description, :text, null: false
      add :status, :text, null: false, default: "new"
      add :internal_notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :location_id,
          references(:locations,
            column: :id,
            name: "issues_location_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false
    end

    create table(:issue_updates, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :message, :text, null: false
      add :sent_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :issue_id,
          references(:issues,
            column: :id,
            name: "issue_updates_issue_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false
    end
  end

  def down do
    drop constraint(:issue_updates, "issue_updates_issue_id_fkey")

    drop table(:issue_updates, prefix: prefix())

    drop constraint(:issues, "issues_location_id_fkey")

    alter table(:issues, prefix: prefix()) do
      remove :location_id
      remove :updated_at
      remove :inserted_at
      remove :internal_notes
      remove :status
      remove :normalized_description
      remove :description
      remove :title
    end

    drop constraint(:reports, "reports_issue_id_fkey")

    alter table(:reports, prefix: prefix()) do
      modify :issue_id, :uuid
    end

    drop table(:issues, prefix: prefix())

    drop constraint(:locations, "locations_parent_id_fkey")

    alter table(:locations, prefix: prefix()) do
      remove :parent_id
      remove :updated_at
      remove :inserted_at
      remove :full_path
      remove :name
    end

    drop constraint(:reports, "reports_location_id_fkey")

    alter table(:reports, prefix: prefix()) do
      modify :location_id, :uuid
    end

    drop table(:locations, prefix: prefix())

    drop table(:reports, prefix: prefix())
  end
end
