defmodule CloseTheLoop.Repo.TenantMigrations.AddAiGuidanceToIssueCategories do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:issue_categories, prefix: prefix()) do
      add :description, :text
      add :ai_guidance, :text
      add :ai_include_keywords, :text
      add :ai_exclude_keywords, :text
      add :ai_examples, :text
    end
  end

  def down do
    alter table(:issue_categories, prefix: prefix()) do
      remove :ai_examples
      remove :ai_exclude_keywords
      remove :ai_include_keywords
      remove :ai_guidance
      remove :description
    end
  end
end
