defmodule CloseTheLoop.Repo.TenantMigrations.ReportIssueIdOptional do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:reports, prefix: prefix()) do
      modify :issue_id, :uuid, null: true
    end
  end

  def down do
    alter table(:reports, prefix: prefix()) do
      modify :issue_id, :uuid, null: false
    end
  end
end
