defmodule CloseTheLoop.Repo.TenantMigrations.AddReportUpdatedAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:reports, prefix: prefix()) do
      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:reports, prefix: prefix()) do
      remove :updated_at
    end
  end
end
