defmodule CloseTheLoop.Repo.TenantMigrations.AddIssueCategoriesAndDedupe do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:issues, prefix: prefix()) do
      add :duplicate_of_issue_id,
          references(:issues,
            column: :id,
            name: "issues_duplicate_of_issue_id_fkey",
            type: :uuid,
            prefix: prefix()
          )
    end

    create table(:issue_categories, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false
      add :label, :text, null: false
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:issue_categories, [:key], name: "issue_categories_unique_key_index")
  end

  def down do
    drop_if_exists unique_index(:issue_categories, [:key],
                     name: "issue_categories_unique_key_index"
                   )

    drop table(:issue_categories, prefix: prefix())

    drop constraint(:issues, "issues_duplicate_of_issue_id_fkey")

    alter table(:issues, prefix: prefix()) do
      remove :duplicate_of_issue_id
    end
  end
end
