defmodule CloseTheLoop.Repo.TenantMigrations.AddReporterNameAndEmail do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:reports, prefix: prefix()) do
      add :reporter_name, :text
      add :reporter_email, :text
    end
  end

  def down do
    alter table(:reports, prefix: prefix()) do
      remove :reporter_email
      remove :reporter_name
    end
  end
end
