import Config
config :ash, policies: [show_policy_breakdowns?: true]

# Configure your database
database_url = System.get_env("DATABASE_URL")

repo_opts =
  if database_url do
    [url: database_url]
  else
    [
      username: "postgres",
      password: "postgres",
      hostname: "localhost",
      # Keep this aligned with the devcontainer/Postgres default.
      database: "close_the_loop_local"
    ]
  end

config :close_the_loop,
       CloseTheLoop.Repo,
       Keyword.merge(
         [
           stacktrace: true,
           show_sensitive_data_on_connection_error: true,
           pool_size: 10
         ],
         repo_opts
       )

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :close_the_loop, CloseTheLoopWeb.Endpoint,
  # Bind to 0.0.0.0 to expose the server to the docker host machine.
  # This makes make the service accessible from any network interface.
  # Change to `ip: {127, 0, 0, 1}` to allow access only from the server machine.
  #
  # E2E tests run the dev server on a dynamic port, so we must also
  # update `url` to avoid emitting asset/websocket URLs pointing to :4000.
  http: [ip: {0, 0, 0, 0}, port: String.to_integer(System.get_env("PORT", "4000"))],
  url: [host: "localhost", port: String.to_integer(System.get_env("PORT", "4000"))],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "yZ1onXK85UC80Zlo9+mQ5vy7bx6UsDA9dtzuyWLVD2ALD1p7038+/jbaX1R172u2",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:close_the_loop, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:close_the_loop, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :close_the_loop, CloseTheLoopWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Gettext translations
      ~r"priv/gettext/.*\.po$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/close_the_loop_web/router\.ex$",
      ~r"lib/close_the_loop_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :close_the_loop, dev_routes: true, token_signing_secret: "IdeqfuBVI3gcRZjsuEAVoIz5uMTXHJqC"

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
