defmodule CloseTheLoop.Repo.Migrations.AddOrganizationInvitations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:organization_invitations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :citext, null: false
      add :token, :text, null: false
      add :role, :text, null: false, default: "staff"
      add :expires_at, :utc_datetime_usec, null: false
      add :accepted_at, :utc_datetime_usec
      add :revoked_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "organization_invitations_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :invited_by_user_id,
          references(:users,
            column: :id,
            name: "organization_invitations_invited_by_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:organization_invitations, [:token],
             name: "organization_invitations_unique_token_index"
           )
  end

  def down do
    drop_if_exists unique_index(:organization_invitations, [:token],
                     name: "organization_invitations_unique_token_index"
                   )

    drop constraint(:organization_invitations, "organization_invitations_organization_id_fkey")

    drop constraint(:organization_invitations, "organization_invitations_invited_by_user_id_fkey")

    drop table(:organization_invitations)
  end
end
