defmodule CloseTheLoop.Repo.Migrations.AddAiGuidanceToIssueCategories do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:organizations) do
      add :ai_business_context, :text
      add :ai_categorization_instructions, :text
    end
  end

  def down do
    alter table(:organizations) do
      remove :ai_categorization_instructions
      remove :ai_business_context
    end
  end
end
