defmodule CloseTheLoop.Repo.Migrations.AddUserOrganizations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_organizations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false, default: "staff"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "user_organizations_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "user_organizations_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:user_organizations, [:user_id, :organization_id],
             name: "user_organizations_unique_user_org_index"
           )
  end

  def down do
    drop_if_exists unique_index(:user_organizations, [:user_id, :organization_id],
                     name: "user_organizations_unique_user_org_index"
                   )

    drop constraint(:user_organizations, "user_organizations_user_id_fkey")

    drop constraint(:user_organizations, "user_organizations_organization_id_fkey")

    drop table(:user_organizations)
  end
end
