defmodule CloseTheLoop.Repo.Migrations.RemoveUserOrgFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      remove :role
      remove :organization_id
    end
  end

  def down do
    alter table(:users) do
      add :organization_id, :uuid
      add :role, :text
    end
  end
end
