defmodule CloseTheLoop.Repo.Migrations.OutboundDelivery do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:outbound_deliveries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :channel, :text, null: false
      add :status, :text, null: false, default: "queued"
      add :provider, :text, null: false
      add :to, :text, null: false
      add :from, :text
      add :subject, :text
      add :body, :text, null: false
      add :tenant, :text
      add :template, :text
      add :related_resource, :text
      add :related_id, :uuid
      add :provider_id, :text
      add :provider_response, :map
      add :error, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:outbound_deliveries, [:to])

    create index(:outbound_deliveries, [:tenant, :inserted_at])

    create index(:outbound_deliveries, [:status, :inserted_at])

    create index(:outbound_deliveries, [:channel, :inserted_at])
  end

  def down do
    drop_if_exists index(:outbound_deliveries, [:channel, :inserted_at])

    drop_if_exists index(:outbound_deliveries, [:status, :inserted_at])

    drop_if_exists index(:outbound_deliveries, [:tenant, :inserted_at])

    drop_if_exists index(:outbound_deliveries, [:to])

    drop table(:outbound_deliveries)
  end
end
