defmodule CloseTheLoop.Repo.Migrations.AddOrgBrandingFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:organizations) do
      add :public_display_name, :text
      add :brand_primary_color, :text
      add :brand_primary_foreground_color, :text
      add :reporter_tagline, :text
      add :reporter_footer_note, :text
    end
  end

  def down do
    alter table(:organizations) do
      remove :reporter_footer_note
      remove :reporter_tagline
      remove :brand_primary_foreground_color
      remove :brand_primary_color
      remove :public_display_name
    end
  end
end
